-
  name: install cert server
  hosts: ca-server
  become: true
  vars_files:
    - ../vars/secrets.yml
  tasks:
    -
      name: prepare remote dir
      ansible.builtin.file:
        path: "{{ remote_dir }}"
        state: directory
        owner: ca-admin
        group: ca-admin
        mode: '0755'
    -
      name: install package rsa
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - easy-rsa=3.0.8-1ubuntu1
        - python3-pexpect
        - acl
        - rsync
        - tree

    -
      name: copy easyrsa files to user dir
      ansible.builtin.copy:
        src: /usr/share/easy-rsa
        dest: "{{ remote_dir }}"
        remote_src: true
        owner: ca-admin
        group: ca-admin
        mode: '0644'

    -
      name: set permission
      ansible.builtin.file:
        path: "{{ remote_dir }}/easy-rsa"
        state: directory
        owner: ca-admin
        group: ca-admin
        mode: '0755'
        recurse: true
        
    -
      name: set config on var.example country
      ansible.builtin.lineinfile:
        path: "{{ remote_dir }}/easy-rsa/vars.example"
        regexp: '^#?set_var EASYRSA_REQ_COUNTRY\s+'
        line: 'set_var EASYRSA_REQ_COUNTRY "RUS"'
        state: present

    -
      name: set config on var.example province
      ansible.builtin.lineinfile:
        path: "{{ remote_dir }}/easy-rsa/vars.example"
        regexp: '^#?set_var EASYRSA_REQ_PROVINCE\s+'
        line: 'set_var EASYRSA_REQ_PROVINCE "Yakutsk"'
        state: present

    -
      name: set config on var.example city
      ansible.builtin.lineinfile:
        path: "{{ remote_dir }}/easy-rsa/vars.example"
        regexp: '^#?set_var EASYRSA_REQ_CITY\s+'
        line: 'set_var EASYRSA_REQ_CITY "Yakutsk City"'
        state: present

    -
      name: set config on var.example org
      ansible.builtin.lineinfile:
        path: "{{ remote_dir }}/easy-rsa/vars.example"
        regexp: '^#?set_var EASYRSA_REQ_ORG\s+'
        line: 'set_var EASYRSA_REQ_ORG "whyorg"'
        state: present

    -
      name: set config on var.example email
      ansible.builtin.lineinfile:
        path: "{{ remote_dir }}/easy-rsa/vars.example"
        regexp: '^#?set_var EASYRSA_REQ_EMAIL\s+'
        line: 'set_var EASYRSA_REQ_EMAIL "whydmitriy@gmail.com"'
        state: present

    -
      name: set config on var.example ou
      ansible.builtin.lineinfile:
        path: "{{ remote_dir }}/easy-rsa/vars.example"
        regexp: '^#?set_var EASYRSA_REQ_OU\s+'
        line: 'set_var EASYRSA_REQ_OU "LLC"'
        state: present

    -
      name: set config on var.example algo
      ansible.builtin.lineinfile:
        path: "{{ remote_dir }}/easy-rsa/vars.example"
        regexp: '^#?set_var EASYRSA_ALGO\s+'
        line: 'set_var EASYRSA_ALGO ec'
        state: present

    -
      name: set config on var.example digest
      ansible.builtin.lineinfile:
        path: "{{ remote_dir }}/easy-rsa/vars.example"
        regexp: '^#?set_var EASYRSA_DIGEST\s+'
        line: 'set_var EASYRSA_DIGEST "sha512"'
        state: present

    -
      name: rename vars.example to vars
      ansible.builtin.command:
        cmd: "mv {{ remote_dir }}/easy-rsa/vars.example {{ remote_dir }}/easy-rsa/vars"
        creates: "{{ remote_dir }}/easy-rsa/vars"
 